---
title: "2021_03_01_RMarkDown_Figures"
author: "Anthony Gutierrez"
date: "3/3/2021"
output: 
  html_document:
    toc: TRUE
    #toc_float: TRUE.. does not work with pdf
    #theme: journal... no pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE,
                      fig.path="../outputs/")
```

# Introduction
Today we will be using R markdown for the second time

```{r}
library(palmerpenguins)
library(tidyverse)
library(here)
library(kableExtra)
```

# Make Plot
```{r, Penfig, fig.width=7, fig.height=5, fig.align='center', fig.cap= "penguin flippers"}
PenguinFigures<- penguins %>%
  ggplot(aes(x = species,
             y=flipper_length_mm,
             color = island))+
  geom_boxplot()
PenguinFigures
  
```

# Make a table 

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

# Tables with kable

```{r}
penguins %>%
  group_by(species) %>%
  summarize(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold = TRUE, color = "white")
```

