---
title: "ggmapping"
author: "Anthony Gutierrez"
date: "3/10/2021"
output: html_document
---
# Load Libraries 
```{r setup, include=FALSE}
library(ggmap)
library(tidyverse)
library(here)
library(ggsn)

ChemData<- read_csv(here("week_7","data","chemicaldata_maunalua.csv"))
glimpse(ChemData)
knitr::opts_chunk$set(echo = TRUE)
```


# Mapping 
```{r}
Oahu<-get_map("Oahu")

#Make a data frame of lon and lat coordinates
WP<-data.frame(lon = -157.7621, lat = 21.27427) # coordinates for Wailupe
# Get base layer
Map1 <-get_map(WP)
# plot it
ggmap(Map1)

Map1<-get_map(WP,zoom = 17)
ggmap(Map1)

Map1<-get_map(WP,zoom = 17, maptype = "satellite")
ggmap(Map1)


ggmap(Map1)+
  geom_point(data = ChemData,
             aes(x = Long, y = Lat, color = Salinity),
             size = 2) +
  scale_color_viridis_c()


ggmap(Map1)+
  geom_point(data = ChemData, 
             aes(x = Long, y = Lat, color = Salinity), 
             size = 2) + 
  scale_color_viridis_c()+
  scalebar( x.min = -157.766, x.max = -157.758,
           y.min = 21.2715, y.max = 21.2785,
            dist = 250, dist_unit = "m", model = "WGS84", 
            transform = TRUE, st.color = "white",
            box.fill = c("yellow", "white"))

```

# How to use geocode
```{r}
geocode("the white house")
geocode("California State University, Northridge")
```

